FROM osrf/ros:humble-desktop-full
ARG USERNAME=ros2user
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME
RUN useradd --uid $USER_UID --gid $USER_GID -m $USERNAME

RUN apt update -y && apt install -y sudo

RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME
RUN chmod 0440 /etc/sudoers.d/$USERNAME
RUN apt update && apt upgrade -y

RUN 	apt install -y \
	ament-cmake \
	ccls \
	python3-colcon-common-extensions \
	python3-pip \
	vim \
	clang \
	clang-format \
	clang-tidy \
	ros-humble-gazebo* \
	ros-humble-rqt* \
	ros-humble-joint-state-publisher-gui \
	ros-humble-rqt-robot-steering \
	ros-humble-rmw-cyclonedds-cpp

#RUN cat "source /home/$USERNAME/catkin_ws/src/entrypoint.sh" >> /home/$USERNAME/.bashrc
#RUN 	echo "source /opt/ros/humble/setup.bash" >> /home/$USERNAME/.bashrc
#RUN	echo "source /usr/share/gazebo/setup.sh" >> /home/$USERNAME/.bashrc && \
	#echo "source /home/$USERNAME/catkin_ws/install/setup.bash" >> /home/$USERNAME/.bashrc

ENV SHELL=/bin/bash
USER $USERNAME
CMD ["/bin/bash"]
